In [1]:
import numpy as np
import pandas as pd
import time

In [3]:
df = pd.read_csv('Social_Network_Ads.csv')

In [4]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [5]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [6]:
df = df[['Age','EstimatedSalary','Purchased']]

In [10]:
df.sample(9)

     Age  EstimatedSalary  Purchased
350   38           113000          1
121   37            72000          0
29    31            18000          0
308   36           125000          1
206   55           130000          1
271   59            76000          1
329   47           107000          1
214   47            43000          0
370   60            46000          1

In [11]:
X = df.iloc[:,0:2]
y = df.iloc[:,-1]

In [12]:
X

     Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [13]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [14]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [15]:
X_scaled.shape

(400, 2)

In [16]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\ipykernel\kernelapp.py", line 758, in start
    self.io_loop.start()
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\tornado\platform\asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\ipykernel\utils.py", line 71, in preserve_context
    return await f(*args, **kwargs)
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\ipykernel\kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\ipykernel\kernelbase.py", line 478, in dispatch_shell
    await result
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\ipykernel\ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\ipykernel\kernelbase.py", line 834, in execute_request
    reply_content = await reply_content
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\ipykernel\ipkernel.py", line 464, in do_execute
    res = shell.run_cell(
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\ipykernel\zmqshell.py", line 663, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\IPython\core\interactiveshell.py", line 3077, in run_cell
    result = self._run_cell(
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\IPython\core\interactiveshell.py", line 3132, in _run_cell
    result = runner(coro)
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\IPython\core\interactiveshell.py", line 3336, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\IPython\core\interactiveshell.py", line 3519, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\IPython\core\interactiveshell.py", line 3579, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\Shivanshu Shukla\AppData\Local\Temp\ipykernel_26348\3280042433.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\tensorflow\__init__.py", line 48, in <module>
    from tensorflow._api.v2 import __internal__
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\tensorflow\_api\v2\__internal__\__init__.py", line 8, in <module>
    from tensorflow._api.v2.__internal__ import autograph
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\tensorflow\_api\v2\__internal__\autograph\__init__.py", line 8, in <module>
    from tensorflow.python.autograph.core.ag_ctx import control_status_ctx # line: 34
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\tensorflow\python\autograph\core\ag_ctx.py", line 21, in <module>
    from tensorflow.python.autograph.utils import ag_logging
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\tensorflow\python\autograph\utils\__init__.py", line 17, in <module>
    from tensorflow.python.autograph.utils.context_managers import control_dependency_on_returns
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\tensorflow\python\autograph\utils\context_managers.py", line 19, in <module>
    from tensorflow.python.framework import ops
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\tensorflow\python\framework\ops.py", line 41, in <module>
    from tensorflow.python import pywrap_tfe
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 25, in <module>
    from tensorflow.python._pywrap_tfe import *

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\ipykernel\kernelapp.py", line 758, in start
    self.io_loop.start()
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\tornado\platform\asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\ipykernel\utils.py", line 71, in preserve_context
    return await f(*args, **kwargs)
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\ipykernel\kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\ipykernel\kernelbase.py", line 478, in dispatch_shell
    await result
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\ipykernel\ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\ipykernel\kernelbase.py", line 834, in execute_request
    reply_content = await reply_content
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\ipykernel\ipkernel.py", line 464, in do_execute
    res = shell.run_cell(
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\ipykernel\zmqshell.py", line 663, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\IPython\core\interactiveshell.py", line 3077, in run_cell
    result = self._run_cell(
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\IPython\core\interactiveshell.py", line 3132, in _run_cell
    result = runner(coro)
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\IPython\core\interactiveshell.py", line 3336, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\IPython\core\interactiveshell.py", line 3519, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\IPython\core\interactiveshell.py", line 3579, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\Shivanshu Shukla\AppData\Local\Temp\ipykernel_26348\3280042433.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\tensorflow\__init__.py", line 48, in <module>
    from tensorflow._api.v2 import __internal__
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\tensorflow\_api\v2\__internal__\__init__.py", line 8, in <module>
    from tensorflow._api.v2.__internal__ import autograph
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\tensorflow\_api\v2\__internal__\autograph\__init__.py", line 8, in <module>
    from tensorflow.python.autograph.core.ag_ctx import control_status_ctx # line: 34
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\tensorflow\python\autograph\core\ag_ctx.py", line 21, in <module>
    from tensorflow.python.autograph.utils import ag_logging
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\tensorflow\python\autograph\utils\__init__.py", line 17, in <module>
    from tensorflow.python.autograph.utils.context_managers import control_dependency_on_returns
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\tensorflow\python\autograph\utils\context_managers.py", line 19, in <module>
    from tensorflow.python.framework import ops
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\tensorflow\python\framework\ops.py", line 44, in <module>
    from tensorflow.python.client import pywrap_tf_session
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\tensorflow\python\client\pywrap_tf_session.py", line 19, in <module>
    from tensorflow.python.client._pywrap_tf_session import *

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\ipykernel\kernelapp.py", line 758, in start
    self.io_loop.start()
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\tornado\platform\asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\ipykernel\utils.py", line 71, in preserve_context
    return await f(*args, **kwargs)
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\ipykernel\kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\ipykernel\kernelbase.py", line 478, in dispatch_shell
    await result
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\ipykernel\ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\ipykernel\kernelbase.py", line 834, in execute_request
    reply_content = await reply_content
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\ipykernel\ipkernel.py", line 464, in do_execute
    res = shell.run_cell(
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\ipykernel\zmqshell.py", line 663, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\IPython\core\interactiveshell.py", line 3077, in run_cell
    result = self._run_cell(
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\IPython\core\interactiveshell.py", line 3132, in _run_cell
    result = runner(coro)
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\IPython\core\interactiveshell.py", line 3336, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\IPython\core\interactiveshell.py", line 3519, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\IPython\core\interactiveshell.py", line 3579, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\Shivanshu Shukla\AppData\Local\Temp\ipykernel_26348\3280042433.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\tensorflow\__init__.py", line 48, in <module>
    from tensorflow._api.v2 import __internal__
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\tensorflow\_api\v2\__internal__\__init__.py", line 8, in <module>
    from tensorflow._api.v2.__internal__ import autograph
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\tensorflow\_api\v2\__internal__\autograph\__init__.py", line 8, in <module>
    from tensorflow.python.autograph.core.ag_ctx import control_status_ctx # line: 34
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\tensorflow\python\autograph\core\ag_ctx.py", line 21, in <module>
    from tensorflow.python.autograph.utils import ag_logging
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\tensorflow\python\autograph\utils\__init__.py", line 17, in <module>
    from tensorflow.python.autograph.utils.context_managers import control_dependency_on_returns
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\tensorflow\python\autograph\utils\context_managers.py", line 19, in <module>
    from tensorflow.python.framework import ops
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\tensorflow\python\framework\ops.py", line 45, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\tensorflow\python\eager\context.py", line 37, in <module>
    from tensorflow.python.eager import execute
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\tensorflow\python\eager\execute.py", line 21, in <module>
    from tensorflow.python.framework import dtypes
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\tensorflow\python\framework\dtypes.py", line 21, in <module>
    import ml_dtypes
  File "C:\Users\Shivanshu Shukla\anaconda3\envs\plant_dl\lib\site-packages\ml_dtypes\__init__.py", line 32, in <module>
    from ml_dtypes._custom_floats import bfloat16

AttributeError: _ARRAY_API not found

ImportError: numpy.core._multiarray_umath failed to import

ImportError: numpy.core.umath failed to import